### PR TITLE
[packaging] Require kmod. Fixes JB#58405

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Review by saukko — APPROVED** [review]
LGTM, extra points on going through https://docs.sailfishos.org/Reference/Software_Packaging/#RPM_packaging_Guidelines on this package.

**Comment by Thaodan** [comment]
Can you take the upstream commit for the last change? 
https://github.com/intel/mic/commit/64074f140509c7b366e5011b331c6f7691621b25

**Comment by Thaodan** [comment]
Here's the change on the more up to date upstream remote: 
https://git.tizen.org/cgit/tools/mic/commit/?id=64074f140509c7b366e5011b331c6f7691621b25

**Comment by martyone** [comment]
I am afraid that would not address the issue I am trying to fix with my change. I am trying to avoid changing a versioned file at build time. The upstream change just moves the value to another versioned file.

**Review by saukko — APPROVED** [review]
OK

**Pull request merged**
